CONNECT'jdbc:derby://localhost:50505/Hotel;create=true;user=triveratravel;password=password';
 
DROP SEQUENCE HIBERNATE_SEQUENCE RESTRICT;
DROP TABLE RESERVATIONS;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000 INCREMENT BY 1;
CREATE TABLE RESERVATIONS (ID INTEGER, ARRIVAL_DATE DATE, NAME VARCHAR(255), NUMBER INTEGER, NIGHTS INTEGER NOT NULL,  STATUS VARCHAR(10));

DISCONNECT;
EXIT; 