DROP TABLE RESERVATIONS;
CREATE TABLE RESERVATIONS (ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1000, Increment by 1), ARRIVAL_DATE DATE, NAME VARCHAR(255), NIGHTS INTEGER NOT NULL,  STATUS VARCHAR(10));
